# Random Numbers

In [13]:
import random 

# Random float from 0 to 1
a = random.random()
print(a)


# Random float from 0 to n
b = random.uniform(1,10)
print(b)


# Random integer from 0 to n(included)
c = random.randint(1,10)
print(c)

# Random integer from 0 to n(excluded)
d = random.randrange(1,10)
print(d)

# Random integer from 0 to n(excluded)
e = random.normalvariate(0,1)
print(e)

0.9117614460253205
2.317473215362873
3
7
2.6730202961743386


In [27]:
# Working with sequences

mylist = list("ABCDEFGH")
print(mylist)

a = random.sample(mylist,3)  # Picks unique choices
print(a)

b = random.choices(mylist,k=3)  # can pick same item twice
print(b)

random.shuffle(mylist)
print(mylist)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
['A', 'F', 'C']
['D', 'B', 'F']
['D', 'A', 'B', 'G', 'E', 'F', 'H', 'C']


In [33]:
random.seed(1)
print(random.random())
print(random.randint(1,10))

print()
random.seed(2)
print(random.random())
print(random.randint(1,10))

print()
random.seed(1)
print(random.random())
print(random.randint(1,10))

print()
random.seed(2)
print(random.random())
print(random.randint(1,10))

# Number with same seed are same
# These numbers are reproducible so, it should not be used for security purposes

0.13436424411240122
2

0.9560342718892494
1

0.13436424411240122
2

0.9560342718892494
1


In [50]:
# Secrets module (can be used for security purposes)
import secrets

mylist2 = list("ABCDEFG")

a = secrets.choice(mylist2)  # It dosent't use seed therefore it is not reproducible
print(a)

E


In [93]:
import numpy as np

a = np.random.randint(5)
print(a)

b = np.random.randint(0,5)
print(b)

c = np.random.randint(0,5,(3,4))
print(c)



0
2
[[1 0 4 2]
 [3 3 0 3]
 [2 4 3 2]]

[[2 4 3 2]
 [1 0 4 2]
 [3 3 0 3]]


In [117]:
np.random.shuffle(c)  # shuffles on single axis
print(c)

[[3 3 0 3]
 [1 0 4 2]
 [2 4 3 2]]
